### ISSUE TITLE
Do we need this repository?

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/legacysurvey.github.io#1]
Currently, this repository appears to be the Nikola output files for DR1(!).  This means that the public site http://legacysurvey.github.io displays very outdated information.  There are several choices:

1. Delete this repository.  This also means that http://legacysurvey.github.io will no longer exist.
2. Update the repository to DR7.  This means that http://legacysurvey.github.io will be a mirror of http://legacysurvey.org.
3. Use this repository for another purpose entirely, for example, high-level discussions of other code in this GitHub group.

**Comment by weaverba137** [comment]
Ping: @dstndstn, @djschlegel, @geordie666

**Comment by geordie666** [comment]
My preference would be to delete this repository, but @dstndstn and @djschlegel might disagree.

**Comment by dstndstn** [comment]
Fine by me!

**Comment by djschlegel** [comment]
I'll concur with the rest of you.  Thanks for cleaning house!

**Comment by weaverba137** [comment]
Thank you, I will clean up presently
